version: 2
jobs:
  one:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, One;date;whoami;pwd;uname -a;sleep 25
      - run:
          mkdir -p my_workspace
      - run: 
          echo "Match my workspaces" > my_worspace/demo
      - persist_to_workspace:
          root: my_workspace
          paths:
            - demo
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Two;date;whoami;pwd;uname -a;sleep 25
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ `cat my_workspace/demo` == "Match my workspaces" ]]; then
            echo "It Worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires: 
            - one
