version: 2
jobs:
  SINGLE-SIGN-ON:
    working_directory: ~/build_workspace
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
            name: Greeting
            command: echo ${BRANCH_NAME}
      - run:
            name: Current Branch
            command: echo Hello, One;date;whoami;pwd;uname -a
      - run:
            mkdir -p my_workspace
      - run: echo "Match my workspaces" > my_workspace/demo;chmod 775 my_workspace/demo;pwd;ls -latr; ls -latr ./my_workspace;cat ./my_workspace/demo
workflows:
  version: 2
  build_and_test:
    jobs:
      - SINGLE-SIGN-ON:
          filters:
            branches:
               only: ${CIRCLE_BRANCH}
