version: 2
jobs:
  SINGLE-SIGN-ON:
    working_directory: ~/build_workspace
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 2d:fb:d0:95:91:b8:3d:0b:6a:b4:17:ee:51:0e:97:65
      -run: echo "Manju"
      - run:
          name: Greeting
          command: echo ${BRANCH_NAME}
      - run:
          name: Current Branch
          command: echo Hello, One;date;whoami;pwd;uname -a
      - run:
            mkdir -p my_workspace
      - run: echo "Match my workspaces" > my_workspace/demo;chmod 775 my_workspace/demo;pwd;ls -latr; ls -latr ./my_workspace;cat ./my_workspace/demo
  Test1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: echo "Parallel Job1"
  Test2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: echo "Parallel Job2"
  Test3:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: echo "Parallel Job3"
  deploy:
    working_directory: ~/deploy_workspace
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Two;date;whoami;pwd;uname -a;ls -latr
      - run: 
          name: Do ls -latr after archiving workspace
          command: ls -latr
      - run: |
          if [[ `cat my_workspace/demo` == "Match my workspaces" ]]; then
            echo "It Worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - SINGLE-SIGN-ON
      - Test1:
          requires:
            - SINGLE-SIGN-ON
          filters:
            branches:
              only: ${CIRCLE_BRANCH}
